# Generated by Django 2.0.1 on 2018-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsstand', '0001_squashed_0004_auto_20180602_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbldbcspellcrafts',
            fields=[
                ('spell', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('item', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tblDBCSpellCrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldbctradeskillcategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.PositiveSmallIntegerField()),
                ('skillline', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tblDBCTradeSkillCategory',
                'managed': False,
            },
        ),
    ]
