# Generated by Django 2.0.1 on 2018-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsstand', '0002_auto_20180219_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblbonusset',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblbuilding',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbccurvepoint',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcenchants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitembonus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemnamedescription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemrandomsuffix',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemreagents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemspell',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemsubclass',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcitemvendorcost',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcpet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcrandenchants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcskilllines',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbldbcspell',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblhousecheck',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitembonusesseen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitemglobal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitemhistorydaily',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitemhistorymonthly',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitemlevelsseen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblitemsummary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblpet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblpetglobal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblpetsummary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblrealm',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblsnapshot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblwowtoken',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='tbldbcitem',
            name='name_enus',
        ),
        migrations.AddField(
            model_name='tbldbcitem',
            name='name',
            field=models.CharField(db_column='name_enus', default='', max_length=250),
        ),
    ]
