# Generated by Django 2.0.1 on 2018-06-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsstand', '0003_auto_20180602_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbldbcitem',
            options={'managed': False},
        ),
    ]
