# Generated by Django 2.0.1 on 2018-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('items', '0001_initial'), ('items', '0002_auto_20180210_2117'), ('items', '0003_auto_20180210_2151')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name_enus', max_length=250)),
                ('quality', models.SmallIntegerField()),
                ('level', models.SmallIntegerField(default=None, null=True)),
                ('item_class', models.SmallIntegerField(db_column='class')),
                ('subclass', models.SmallIntegerField()),
                ('icon', models.CharField(max_length=120)),
                ('stacksize', models.SmallIntegerField(default=None, null=True)),
                ('auctionable', models.SmallIntegerField(default=None, null=True)),
                ('type', models.SmallIntegerField(default=None, null=True)),
                ('requiredlevel', models.SmallIntegerField(default=None, null=True)),
                ('requiredskill', models.SmallIntegerField(default=None, null=True)),
                ('buyfromvendor', models.IntegerField(blank=True, default=None, null=True)),
                ('selltovendor', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'tblDBCItem',
                'ordering': ['id'],
            },
        ),
    ]
