# Generated by Django 2.0.1 on 2018-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_squashed_0003_auto_20180210_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blizzard_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
