# Generated by Django 2.0.1 on 2018-06-03 03:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('items', '0002_item_blizzard_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
