# Generated by Django 2.0.1 on 2018-06-03 01:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realm',
            table=None,
        ),
    ]
