# Generated by Django 2.0.1 on 2018-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_auto_20180602_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='house',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
