# Generated by Django 2.0.1 on 2018-08-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realms', '0003_auto_20180603_1635'),
        ('items', '0003_auto_20180602_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auc', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(help_text='The Character that listed this Auction', max_length=32)),
                ('bid', models.PositiveIntegerField()),
                ('buyout', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('timeLeft', models.CharField(choices=[('Very Long', 'VERY_LONG'), ('Long', 'LONG'), ('Short', 'SHORT')], max_length=16)),
                ('rand', models.IntegerField()),
                ('seed', models.IntegerField()),
                ('context', models.IntegerField()),
                ('bonusLists', models.CharField(max_length=256)),
                ('item', models.ForeignKey(help_text='The Item being sold', on_delete=django.db.models.deletion.PROTECT, to='items.Item')),
                ('ownerRealm', models.ForeignKey(help_text='The Realm on which this Auction is listed on.', on_delete=django.db.models.deletion.PROTECT, to='realms.Realm')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionData',
            fields=[
                ('house', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nextcheck', models.DateTimeField(blank=True, null=True)),
                ('lastdaily', models.DateField(blank=True, null=True)),
                ('lastcheck', models.DateTimeField(blank=True, null=True)),
                ('lastcheckresult', models.TextField(blank=True, null=True)),
                ('lastchecksuccess', models.DateTimeField(blank=True, null=True)),
                ('lastchecksuccessresult', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
