# Generated by Django 2.0.1 on 2018-08-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ownerRealm',
            field=models.ForeignKey(help_text='The Realm on which this Auction is listed on.', on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='realms.Realm'),
        ),
    ]
