# Generated by Django 2.0.1 on 2018-09-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouses', '0002_auto_20180814_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bonusLists',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='context',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='rand',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='seed',
        ),
        migrations.AddField(
            model_name='auctiondata',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
