# Generated by Django 2.0.1 on 2018-09-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouses', '0003_auto_20180909_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(help_text='The Item being sold', on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='items.Item'),
        ),
    ]
