# Generated by Django 2.0.1 on 2018-09-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_auto_20180602_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillline', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.PROTECT, related_name='reagent_for', to='items.Item', verbose_name='Item Made')),
                ('reagent', models.ForeignKey(db_column='reagent', on_delete=django.db.models.deletion.PROTECT, to='items.Item')),
            ],
            options={
                'ordering': ['spell'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blizzard_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512, verbose_name='Spell Description')),
                ('cooldown', models.IntegerField(default=0)),
                ('skillline', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('qtymade', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('expansion', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('crafteditem', models.ForeignKey(db_column='crafteditem', on_delete=django.db.models.deletion.PROTECT, related_name='crafting_recipe', to='items.Item', verbose_name='Crafted Item')),
                ('reagents', models.ManyToManyField(related_name='recipes', through='recipes.Ingredient', to='items.Item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('reagent', 'spell')},
        ),
    ]
