# Generated by Django 2.0.1 on 2018-02-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('recipes', '0001_initial'), ('recipes', '0002_auto_20180210_2118'), ('recipes', '0003_auto_20180210_2148'), ('recipes', '0004_auto_20180210_2151')]

    initial = True

    dependencies = [
        ('items', '0002_auto_20180210_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillline', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.PROTECT, related_name='reagent_for', to='items.Item')),
                ('reagent', models.ForeignKey(db_column='reagent', on_delete=django.db.models.deletion.PROTECT, to='items.Item')),
            ],
            options={
                'db_table': 'tblDBCItemReagents',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('cooldown', models.IntegerField(default=0)),
                ('skillline', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('qtymade', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('expansion', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('crafteditem', models.ForeignKey(db_column='crafteditem', on_delete=django.db.models.deletion.PROTECT, related_name='crafting_recipe', to='items.Item', verbose_name='Crafting Recipe')),
                ('reagents', models.ManyToManyField(related_name='recipes', through='recipes.Ingredient', to='items.Item')),
            ],
            options={
                'db_table': 'tblDBCSpell',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='spell',
            field=models.ForeignKey(blank=True, db_column='spell', null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.Recipe'),
        ),
    ]
