# Generated by Django 2.0.1 on 2018-02-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_squashed_0004_auto_20180210_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='crafteditem',
            field=models.ForeignKey(db_column='crafteditem', on_delete=django.db.models.deletion.PROTECT, related_name='crafting_recipe', to='items.Item', verbose_name='Crafted Item'),
        ),
    ]
