# Generated by Django 2.0.1 on 2018-02-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180210_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': []},
        ),
    ]
