# Generated by Django 2.0.1 on 2018-09-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180926_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='items.Item', verbose_name='Item Crafted'),
        ),
    ]
