# Generated by Django 2.0.1 on 2018-10-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180926_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='crafteditem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crafting_recipe', to='items.Item', verbose_name='Crafted Item'),
        ),
    ]
