# Generated by Django 2.0.1 on 2018-02-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180210_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': False, 'ordering': []},
        ),
    ]
