# Generated by Django 2.0.1 on 2018-06-03 01:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('recipes', '0008_auto_20180210_2353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
